# Generated by Django 5.2.8 on 2025-11-15 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_alter_player_create_at_alter_player_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
